capturable_point:
 blocked: '&cЗаблокировано'
 active: '&2Активно'
 destroyed: '&0Уничтожено'
 hp_text:
  - '%status%'
  - '%team%'
  - 'Здоровье: %hp%'

time_to_start: 20
respawn_time: 5

database_url: "jdbc:sqlite:siegearena.sqlite"

spawn:
 world: "world"
 x: 0.0
 y: 64.0
 z: 0.0
 yaw: 0.0
 pitch: 0.0